6 ticket2a get request developer only
Gayle-Thompson-Igwebike/GOOD-PR-v1 pull request #16
Opened 2023-07-29 13:27 UTC by Gayle-Thompson-Igwebike

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

#6-GET-REQUEST-GAYLE

## GET REQUEST 

Created a GET request and tested it. 

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #6 

## Checklist:

- [y ] My code follows the style guidelines of this project
- [ y] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-07-31 18:38 UTC, AndrianaOS requested changes
Great code Gayle, just made a few suggestions to some of the responses.
Remember to push your code from this afternoon in as well

2023-07-31 18:38 UTC, AndrianaOS commented on server/getPRCount.js
> +    console.log(`Total Number of pull request contributions from ${repoOwner} in this repo is: ${pullRequestCount}`);
instead of console logging the response, return it as a res.send/res.json

2023-07-31 18:38 UTC, AndrianaOS commented on server/getPRCount.js
> +    console.error("Error fetching pull requests:", error);
Place a status code in the catch so if it catches an error it doesn't still have the status as 200. 
So something like: 
`res.status(500).json({error: error})`

2023-07-31 18:38 UTC, AndrianaOS commented on server/getPRCount.js
> +    const pullRequestCount = response.data.length;
Put an if statement in there so if theres an error, it throws the error message to the catch block
`if(!response.data) {res.send("Some error message")}
else {res.status(200).json({message: "Some success string"})}`

2023-07-31 18:38 UTC, AndrianaOS commented on server/index.js
> +const port = 8000;
Push the rest of the code we did this afternoon to this branch

2023-07-31 18:39 UTC, AndrianaOS commented
Also remember to pull before you push changes to resolve the merge conflict in this branch

2023-08-10 10:31 UTC, closed without merging

2023-08-10 10:31 UTC, Gayle-Thompson-Igwebike commented
closed this branch as the get request was made on another branch - get-request