10-Registaration Form-Saghar Hosseinmardi
Gayle-Thompson-Igwebike/GOOD-PR-v1 pull request #17
Opened 2023-07-29 13:36 UTC by SagharHosseinmardi

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

1. Added dependencies.
2. Rename index.js to server.js.
3. Created the registration form.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #10 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-08-02 15:44 UTC, AndrianaOS requested changes
Ive made some comments on some little changes. You can ignore the useState comments for now as the code works and refactor the code later on but change the fetch url to the render backend url, remove the console.logs and change the text area in the project brief section into an input instead.
Once that is done, it can be merged

2023-08-02 15:44 UTC, AndrianaOS commented on client/src/components/Form/Form.js
> +  const [githubUsername4, setGithubUsername4] = useState("");
We discussed putting lines 4 to 24 in a single useState already. As we said this is ok for now, we will refactor the code as we go along

2023-08-02 15:44 UTC, AndrianaOS commented on client/src/components/Form/Form.js
> +      const response = await fetch("http://localhost:8000/submit-form", {
Change the fetch url to the render url for the backend so we can all run the code as we all dont have the local environment this code runs from

2023-08-02 15:44 UTC, AndrianaOS commented on client/src/components/Form/Form.js
> +      console.log(data);
Remember to take this out so its not console logging information every time it runs

2023-08-02 15:44 UTC, AndrianaOS commented on client/src/components/Form/Form.js
> +        <textarea
you can change this `textarea` into an input as it will only be accepting the url of the project brief

2023-08-02 20:19 UTC, SagharHosseinmardi commented on client/src/components/Form/Form.js
> +  const [githubUsername4, setGithubUsername4] = useState("");
This part has been refactored.

2023-08-03 13:33 UTC, AndrianaOS approved these changes
All good. Thank you for the changes Saghar

2023-08-03 13:34 UTC, AndrianaOS approved these changes

2023-08-03 17:23 UTC, merged